# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yamldo < Formula
  desc "Create YAML documents from a directory tree or a ZIP archive."
  homepage "https://github.com/lucasepe/yamldo"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lucasepe/yamldo/releases/download/v0.1.0/yamldo_0.1.0_darwin_amd64.tar.gz"
      sha256 "77d0e12b2fe2641a33a97bc817de87efa98fd2d3aa254a28a789bdfc29d5db82"

      def install
        bin.install "yamldo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lucasepe/yamldo/releases/download/v0.1.0/yamldo_0.1.0_darwin_arm64.tar.gz"
      sha256 "681133833a9973a2e7899c5371993578e86f45e264d368bd0c5954ced5dfcb83"

      def install
        bin.install "yamldo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lucasepe/yamldo/releases/download/v0.1.0/yamldo_0.1.0_linux_amd64.tar.gz"
      sha256 "c406988760bc1c3b96b6658710b599a9cc69055f8b2e7967f032056e23828c32"

      def install
        bin.install "yamldo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucasepe/yamldo/releases/download/v0.1.0/yamldo_0.1.0_linux_arm64.tar.gz"
      sha256 "6874a26bd5df7361cb4115e7442cb69e9f18a54779fee8cbfe89a3be9abdea5f"

      def install
        bin.install "yamldo"
      end
    end
  end
end
